import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Bet Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfitSans.variable} antialiased`}
      >
        <div className="flex flex-col min-h-svh">
          <Header />
          <main className="flex flex-1 flex-col">
            <div className="w-full mx-auto px-4 lg:max-w-7xl">
              <div className="grid grid-cols-[240px_minmax(0,1fr)] gap-5">
                <aside>Left Side bar</aside>
                <main>
                  {children}
                </main>
              </div>
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
